### ISSUE TITLE
팀 프로젝트 주제선정

### ISSUE THREAD

**Issue by shine-jung** [LeeShinwon/2021OSS_teamproject#1]
원하는 주제를 comment로 남겨주세요

**Comment by shine-jung** [comment]
축구 팀 선수 정보

이름, 국적, 소속 리그, 소속 팀, 나이, 골 수, 어시스트 수, etc..

**Comment by LeeShinwon** [comment]
스팸 전화, 스팸 문자 조회
전화번호, 내용, 등록된 횟수, 문자인지 전화인지

**Comment by shine-jung** [comment]
GMO 식품, 비건, 베지테리언(식품관련)
