### ISSUE TITLE
read 함수 구현에 관하여

### ISSUE THREAD

**Issue by shine-jung** [LeeShinwon/2021OSS_teamproject#5]
convert.c를 쓰지 않고 문자열 배열을 이용해서 음식의 종류를 출력하는 것은 어떤가요?

**Comment by LeeShinwon** [comment]
좋은 생각인 것 같아요.

**Comment by shine-jung** [comment]
넵 반영해놨습니다.
그런데 PR 내역이 협업 평가에 들어가네요. 분석하기 함수 완성하고 pull request 보내겠습니다.
내일까지 코드 완성하고 월요일에 wiki page 작성 마무리하고 제출합시다!

**Comment by LeeShinwon** [comment]
넵. 그런데 제품추가나 제품 수정을 할때, 어떤 것이 몇 번인지 잘 알 수 없을 것 같아 간단하게 그것을 보여주는 코드를 추가로 넣어도 괜찮을까요?

**Comment by shine-jung** [comment]
네네! 그걸 빠뜨렸네요ㅠㅠ 감사합니다

**Comment by LeeShinwon** [comment]
노트북에 깃허브 계정이 잘못 등록되어 있었는지, LeeShinwon으로 커밋, 푸시되지 않고, Songdabin으로 올라갔습니다.
<img width="1188" alt="스크린샷 2021-05-09 오후 12 52 11" src="https://user-images.githubusercontent.com/82192923/117560071-7bfa9e00-b0c5-11eb-906b-fe6a5a00ff7b.png">

**Comment by shine-jung** [comment]
혹시 모르니 계정이 잘못 등록되어 있어서 다른 계정으로 활동 되었다고 교수님께 알려드려요!

**Comment by LeeShinwon** [comment]
네 알겠습니다.
