### ISSUE TITLE
진행 상황

### ISSUE THREAD

**Issue by LeeShinwon** [LeeShinwon/2021OSS_teamproject#8]
이번 주, 과제 제출을 위해 해야 할 것들이 더 있을까요?

**Comment by LeeShinwon** [comment]
위키에 페이지를 더 추가해 두었습니다.

**Comment by shine-jung** [comment]
함수 구현을 모두 마쳐서 더 이상 코드를 수정하지 않아도 될 것 같습니다.
위키에 링크 넣어주셔서 감사합니다.

**Comment by shine-jung** [comment]
혹시 참고자료 위키페이지에 있는 채식주의 표 출처가 있을까요?

**Comment by LeeShinwon** [comment]
https://www.skcareersjournal.com/1490

**Comment by LeeShinwon** [comment]
여기서 가져왔습니다

**Comment by shine-jung** [comment]
감사합니다. 더 추가해야할 것은 이제 없을거 같습니다.

**Comment by shine-jung** [comment]
이제 제출하면 될 것 같아요. 히즈넷이 빨리 복구 됐으면 좋겠습니다ㅠㅠ

**Comment by LeeShinwon** [comment]
수고하셨습니다. 빨리 히즈넷이 복구되어야할텐데ㅠㅠㅠ

**Comment by LeeShinwon** [comment]
방금 히즈넷이 복구된 것 같아요! 들어가 보세요

**Comment by shine-jung** [comment]
감사합니다 ㅎㅎ

**Comment by shine-jung** [comment]
팀 프로젝트 고생 많으셨습니다! 이번 프로젝트 하면서 재미있었습니다.

**Comment by LeeShinwon** [comment]
고생 많으셨습니다. 저도 너무 재밌었습니다^^

**Comment by LeeShinwon** [comment]
이슈를 모두 close 하겠습니다!
